### ISSUE TITLE
Recaps for epic

### ISSUE THREAD

**Issue by mikron-ia** [mikron-ia/rpg-hub-backend#26]
*NOTE: this is going to be a stop-gap measure*

`Epic` in its current form is incapable of providing 'current' record, required by front. This will likely be delivered in future via a module, or some more extensive `Epic` architecture. For the moment, following is suggested:

* [x] `Recap` object, stored in DB
* [x] Architecture for data
* [ ] `retrieveMostRecent()` method for `Recap` factory
* [ ] Delivery system in a `/epic/` controller or `Epic` factory
